### PR TITLE
Calculate max buffer count in real time

### PR DESCRIPTION
**Pull request by jiangteng**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

...

### CODE REVIEW

**Comment by dreampiggy** [comment]
This calculation is called 60 times a second.

Are you sure you want this ? The sysctl call is not cheap because it's a kernal call.

**Comment by jiangteng** [comment]
Check every 4 times, which can be controlled at 15 times a second. But there will still be a read cache operation.

Reducing decoded frame bytes can reduce some cases, but doesn't essentially solve the problem. Would it be better if the update maxBufferCount was executed in fetchQueue?

**Comment by dreampiggy** [comment]
Why closing this ? Is #3424 issue closed ?

**Comment by jiangteng** [comment]
Run it internally first, and reopen it if it works

**Pull request closed without merging**
