### PR TITLE
Synchronise getter and setter of the cancelled property of the SDWebImageCombinedOperation

### PR DESCRIPTION
**Pull request by alexander-gaidukov**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: https://github.com/SDWebImage/SDWebImage/issues/3392

### Pull Request Description

This pull request provides synchronization of the getter and setter of the `cancelled` property of the `SDWebImageCombinedOperation`. This avoids data races.

### CODE REVIEW

**Comment by dreampiggy** [comment]
Do not use queue for locking.

Just, write a custom getter, then use the @synchronized (self) to guard.

Or you can use os_unfair_lock, we have `SD_LOCK_INIT` macro

**Comment by alexander-gaidukov** [comment]
> Do not use queue for locking. This is bad both from the design of GCD as well as performance
> 
> Just, write a custom getter, then use the @synchronized (self) to guard.
> 
> Or you can use os_unfair_lock, we have `SD_LOCK_INIT` macro (use that to replace current `@synchronized(self)`)

Thanks for your suggestion. I've changed the PR accordingly.

**Comment by dreampiggy** [comment]
LGTM. I'll merge it

**Comment by dreampiggy** [comment]
Seems during the review, I ignore the wrong earily return of that line, which will cause the lock be unbalanced.

Instead of just fixing this issue, I suggest to use `@onExit` to ensure the lock been destroyed, which seems silly mistake.

**Comment by dreampiggy** [comment]
The os_unfair_lock and OSSpinLock can not use as recusive lock.

Here may be case that user's custom cancel completion may access `isCancelled` and cause recursive.

To solve this issue quickly, I deceide to rollback the https://github.com/SDWebImage/SDWebImage/pull/3393

**Pull request merged**
