### PR TITLE
Allows the transformer to preserve the UIImage metadata like image format

### LINKED ISSUE #3687: issue with `SDImageCache.sharedImageCache`
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macos
 Platform Version        | 17.2
 SDWebImage Version      | 5.19.0
 Integration Method      | cocoapods
 Xcode Version           | e.g. Xcode 14
 Repro rate              | e.g. all the time (100%) 

### Issue Description and Steps

I have an issue with `SDImageCache.removeImageForKeyCacheTypeCompletion` when used in conjonction with transformers
Here is my use case (i use Javascript code here, just see it as pseudo code. I use Nativescript which directly calls the native method)
* set image :
```js
if (transformers.length > 0) {
                    context.setValueForKey(SDImagePipelineTransformer.transformerWithTransformers(transformers), SDWebImageContextImageTransformer);
                }
                this.mCacheKey = SDWebImageManager.sharedManager.cacheKeyForURLContext(uri, context);
                this.nativeImageViewProtected.sd_setImageWithURLPlaceholderImageOptionsContextProgressCompleted(uri, this.placeholderImage, options, context, this.onLoadProgress, this.handleImageLoaded);
``` 
* update the source  image on disk
* remove from cache
```js
SDImageCache.sharedImageCache.removeImageForKeyCacheTypeCompletion(this.mCacheKey, SDImageCacheType.All, onCompletion);
```
* once done set the image again when the same code as above.

That process works perfectly fine when there is no transform. But when there is a transform ` SDWebImageManager.sharedManager.cacheKeyForURLContext(uri, context)` does not seem the return the correct key because it is the image without transform which is removed from cache and not the image "with" transform.
To be even clearer i see that  `SDWebImage`  caches 2 images where there is a transform: the source image and the image transformed. I would expect `SDWebImageManager.sharedManager.cacheKeyForURLContext(uri, context)` to return the key for the transformed image (which it kind of look like as i see the transform "keys" in the returned string).
But when i use that key to remove from cache i see that the "source cache image" is removed (from disk) but not the "transformed image".
Do you have any idea?
On that note in my case uri is a local file. Why is the "source image" cached again on disk while it is just a "copy" of the image pointed by uri? Seems unecessary and thus uses unecessary space.

Thanks

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### PR description

This can make it by defaults to still use JPEG encoding for JPEG thumbnail image

This close #3687

### CODE REVIEW

**Comment by bdaz** [comment]
Hey @dreampiggy — FYI that this change will cause issues when a transformer transforms an original JPG image in a way that requires transparency (e.g., corner rounding). Because `preservesImageMetadata` defaults to `YES`, the transformed image is cached to disk as JPG, thus losing the transparency. 

Not sure if you've considered this case, but it caught me by surprise when I suddenly saw images appearing in my app without the corner rounding I expected. Easy fix by setting `preservesImageMetadata` to `NO`, but raising here because it's not clear to me that `YES` is the right default.

**Comment by dreampiggy** [comment]
This only contains issue if your `original image` comes from JPEG

So, why does that contains alpha channel ? Are you create alpha channel by your own ?

**Comment by dreampiggy** [comment]
A stupid way is to set the transformer (it's per-transformer property) called `preservesImageMetadata = NO`

**Comment by dreampiggy** [comment]
Or if you still want **A smart policy** to guess what's the image foramt used for encoding. Maybe it's still possible.


+. If the `UIImage.sd_imageFormat` is unkown:
  +. Detect the `UIImage`'s alpha channel
    +. If all of pixels are non-transparent ( by enumerate all the pixels, using for-in loop)
  +. then, use JPEG 
    +. else
  +. use PNG

**Comment by dreampiggy** [comment]
>  but raising here because it's not clear to me that YES is the right default.

Do you want the `NO` as defaults ? Maybe a better way it's to use global options for low version migration.

But at that time, I believe the default `YES` is more suitable for common transformers (Because the transformed image does not loss some information like *where this original image comes from*)

**Comment by TarasGordienko** [comment]
Hey @dreampiggy. Is writing custom transformers the only way to avoid preserving metadata? Having it in the initializer would allow to have old or new behavior.

**Comment by dreampiggy** [comment]
> Hey @dreampiggy. Is writing custom transformers the only way to avoid preserving metadata? Having it in the initializer would allow to have old or new behavior.

Just set the `transformer.preserveMetadata = NO`, it's a property

**Comment by dreampiggy** [comment]
> > Hey @dreampiggy. Is writing custom transformers the only way to avoid preserving metadata? Having it in the initializer would allow to have old or new behavior.
> 
> Just set the `transformer.preserveMetadata = NO`, it's a property.
> 
> Or, For transformer who don't has this property built-in, in Objc, you can use Category to add a method to any class, add a method called `preserveMetadata` and return NO

Is this is still not `easy-to-use`, for our SDWebImage maintained transformer `SDXXXTransformer`, we can inherited them from a Basic class, and has `preserveMetadata` readwrite property for you to custom.

**Pull request merged**
