### PR TITLE
Fix our HEIC coder to encode `timed image sequences` instead of `non-timed image gallery` for HEIC encoding

### LINKED ISSUE #3726: Support HEIC Sequence image encoding via `public.heics` UTI but not `public.heic` UTI for App compatibility
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Feature requests

Apple's ImageIO in iOS 18 expose the public API for: https://developer.apple.com/documentation/uniformtypeidentifiers/uttype-swift.struct/heics

It's back-deployed supported on iOS 16-17 as well.

Currently our `SDImageHEICCoder` does not support animated image encoding. It's time to update and provide the support by ImageIO framework

CC @VaslD

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

Also, some little behavior changes, the `format` arg in animated coder does not help for anything.

This close #3726

### CODE REVIEW

**Comment by dreampiggy** [comment]
CC @VaslD

**Comment by VaslD** [comment]
If I understood correctly, this would simply change HEIC encoding to HEICS, right? Diff looks fine.

**Comment by dreampiggy** [comment]
> If I understood correctly, this would simply change HEIC encoding to HEICS, right? Diff looks fine.

Can you have a try with this branch in your App ? Seems your original issue points out that you use SD for some encoding use case

**Comment by dreampiggy** [comment]
@VaslD Have you tried to use ImageIO and `public.heics` encoding on the GitHub action environment ? Which seems use Mac Virtualization framework

```
2024-07-23 07:01:31.203095+0000 xctest[4842:26689] [] (Fig) signalled err=-15474
2024-07-23 07:01:31.274707+0000 xctest[4842:26689] [] (Fig) signalled err=-17108
        imageProperties = dict(
            Orientation = 1
            kCGImageDestinationEmbedThumbnail = false
            kCGImageDestinationLossyCompressionQuality = 1
            {HEICS} = dict(
                DelayTime = 0.040000
            )
        )
2024-07-23 07:01:31.339477+0000 xctest[4842:26689] /Users/runner/work/SDWebImage/SDWebImage/Tests/Tests/SDImageCoderTests.m:701 expected: not nil/null, got: nil/null
```

See: https://github.com/SDWebImage/SDWebImage/actions/runs/10054041860/job/27787889449?pr=3728

I found this error log and it can not encoded succefully.

However, when switch to `public.heic` to use the same code (and encode **Multi-frame** non-timed HEIC image), it can encode successfully.

**Comment by dreampiggy** [comment]
@VaslD And also, when running on my local M1 Mac's iPhone 17.0 simulator, it always produce this warning log:

```
est Case '-[SDWebImageDecoderTests test16ThatHEICAnimatedWorks]' started.
unrecognised property key2024-07-23 15:18:00.795065+0800 xctest[5470:56746] unrecognised property key
        imageProperties = dict(
            Orientation = 1
            {HEICS} = dict(
                DelayTime = 0.040000
            )
        )
```

Is this `public.heics` actually private API or something buggy in old version (before iOS 18 ?)

**Comment by VaslD** [comment]
Sorry, another project took priority. I didn't find time to test this. Will try this weekend if that's not too late.

Like I said in another post, `public.heics` was returned by `CGImageDestinationCopyTypeIdentifiers()` down to iOS 14-something as far as I can tell, so I wouldn't consider it private API. Besides, keys like `kCGImagePropertyHEICSDictionary` apparently had "HEICS" in their name. If you ask me, I'd say they were explicitly designed for HEICS, and using them with `public.heic` shouldn't even be valid.

Can you pin point the offending property causing those warnings? "unrecognised property key" really doesn't say much.

Can't say for GitHub's VM, but when I experimented with HEICS I didn't get any runtime warning or error when running my demo.

**Comment by dreampiggy** [comment]
> If you ask me, I'd say they were explicitly designed for HEICS, and using them with public.heic shouldn't even be valid.

Seems not related issue. There are no `public.heic` in code, after this MR been merged. All the test above based on the `public.heics`

> Can you pin point the offending property causing those warnings? "unrecognised property key" really doesn't say much.
I don't know actually. At least using only one property called `kCGImagePropertyHEICSDictionary` still triggeres the warning
 when you run in the Xcode unit test environment and iPhone simulator (not test the real device)

Just use SDWebImage's `test16ThatHEICAnimatedWorks` case

**Comment by dreampiggy** [comment]
See this: https://github.com/SDWebImage/SDWebImage/pull/3728

This is based one the current HEAD commit

**Comment by VaslD** [comment]
Just updated to 5.19.5 and tried the new `SDImageHEICCoder`. It seemed to produce animations as expected. Thanks!

**Comment by dreampiggy** [comment]
@VaslD Havn't create a radar. Can you create one ?

If I'm not buzy, I can create one in this weekend.

A hint: After 2020, in 4 years, each new iOS beta break one of SDWebImage's ImageIO usage...😣

**Comment by VaslD** [comment]
Done. FB14537754

> CGImageDestinationFinalize Does Not Write Data on iOS 18
>
> The sample app exports animations in HEICS format using ImageIO. When running on iOS 17 and below, the app writes an animation file in Documents. When running on iOS 18 beta 3 and 4, CGImageDestinationFinalize returns true without writing any data to CGImageDestination (specifically when created with CGImageDestinationCreateWithData and CGImageDestinationCreateWithURL). The app detects this bug and return early, break on source or remove 0-length guard to observe unexpected behavior.

---

> A hint: After 2020, in 4 years, each new iOS beta break one of SDWebImage's ImageIO usage...😣

And that's depressing.

**Pull request merged**
