### PR TITLE
Performance: Introduce frame pool for SDAnimatedImage playback. Solve when multiple image view references the same URL image cause un-wanted decode which waste RAM/CPU

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

This is the second solution for #3515

### CODE REVIEW

**Comment by icoder33** [comment]
Hi I saw your pr here 
I found sd has bad performance on large gif (both use UIImageView/SDAnimationView)
I try to show some gif (sometimes its big cause server dont handle it) in my feed list
and it will crash like that
image

It will crash in recent  sd version，in your pr case it better than before but still has bad performance and finally crash cause by memory problem

**Comment by dreampiggy** [comment]
@icoder33
Your stacktrace is `Encoding`, not `Decoding`. It does not related to this PR at all.

You can fire a new issue and provide a demo to reproduce. Your stacktrace shows that you're triggering `Image Decoding when download a web image`

This logic only happenes when you use `Transformer` or `Thumbnail` or the encode format does not match what you query. So this maybe some configuration related to your problem.

**Comment by icoder33** [comment]
感谢回复，这边似乎定位到了问题 是由于某个版本这边大图webp有些问题 所以全局采用了推荐的保护方式

这里全局增加的ScaleDown会导致Gif的carsh


这边我把demo附在下方 之前那张大的问题图片(服务端未控制的情况)会导致页面非常卡顿甚至crash 这边也一并贴在下方 所以这边我不应该把ScaleDown增加在全局吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SDWebImage/SDWebImage"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月15日(星期一) 中午11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SDWebImage/SDWebImage] Performance: Introduce frame pool for SDAnimatedImage playback. Solve when multiple image view references the same URL image cause un-wanted decode which waste RAM/CPU (PR #3524)





 
@icoder33
 Your stacktrace is Encoding, not Decoding. It does not related to this PR at all.
 
You can fire a new issue and provide a demo to reproduce. Your stacktrace shows that you're triggering Image Decoding when download a web image
 
This logic only happenes when you use Transformer or Thumbnail or the encode format does not match what you query. So this maybe some configuration related to your problem.

**Comment by dreampiggy** [comment]
@icoder33 https://github.com/SDWebImage/SDWebImage/issues/new/

**Comment by dreampiggy** [comment]
#icoder33 

Long time no reply. But this optimiation is worked in the Demo App and the SDWebImageSwiftUI, so it's time to merge and release new minor version

**Comment by dreampiggy** [comment]
Hint:

Tencent's Devs told they use `NSCache` to hold frame buffer which can get benefit than simple `NSMutableDictionary`, in : https://cloud.tencent.com/developer/article/2285760

But I'm not sure whether this cause more issue than solve. Because `SDMemoryCache` use `NSCache` and there are lots of report for crashes or behavior issue about that. So in this PR I still choose to use `NSMutableDictionary`.

If someone has more idea about this, feel free to change this into NSCache with performance report (Instrument result is OK) and submit PR

**Pull request merged**
