### PR TITLE
Revert explicitly set *_DEPLOYMENT_TARGET inside the Tests Xcode project

### PR DESCRIPTION
**Pull request by bpoplauschi**
Initially changed in #2709

### CODE REVIEW

**Comment by dreampiggy** [comment]
See: https://travis-ci.org/SDWebImage/SDWebImage/builds/524498448#L4400

image


I'm sure this warning exists. If you remove this GUI part Xcode config for deployment target version.

Maybe it's an Xcode bug. But all the way I've tried, including the `Podfile` for Test project, using xcconfig. The only way I found works is that changing the config solve this warning. 

Actually, seems this change, does not cause anything issue...Since it's just a test project, which can even be deployment version greater than iOS 8.0(macOS 10.10). Like our example project, which min deployment target version is iOS 11(macOS 10.13)

**Comment by dreampiggy** [comment]
Why I change this, maybe related to #2711.

During my writing of test cases, some of macOS API, like `NSKeyedArchiver`, which will trigger a warning because Xcode thinks you're using a macOS 10.6 deployment target version.

**Comment by dreampiggy** [comment]
Seems after the Podfile changes with #2761. This strange warning disappeared ? 😕 

image

If so, let's try to merge back this.

**Comment by dreampiggy** [comment]
Still here in Travis-CI.

https://travis-ci.org/SDWebImage/SDWebImage/builds/552320883?utm_source=github_status

image

Need we just ignore this warning ?

**Comment by dreampiggy** [comment]
It's OK to revert back. Since this warning does not cause any issue. It's issue of KVOController and does not cause any runtime issue.

**Comment by bpoplauschi** [comment]
Thanks @dreampiggy

**Pull request merged**
