### PR TITLE
Totally remove the MapKit integration, including Source Code, Subspec, SwiftPM, fix the issue of SwiftPM on Xcode 11.4 Beta, make it scalable

### PR DESCRIPTION
**Pull request by dreampiggy**
Make it scalable in the future. For example, in SDWebImage 6.0.0, we may provide a Swift overlay shim framework, which may need subspec.

### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: #2941 
This close #2944 

### Pull Request Description

See #2941 see the reason.

The new MapKit framework repo is here: https://github.com/SDWebImage/SDWebImageMapKitPlugin

### CODE REVIEW

**Comment by bpoplauschi** [comment]
@dreampiggy glad to see you are working on this project of separating `MapKit` into its own repo.
I think it's a good idea, I wanted to do it a few times, but there were always more pressing issues :)

My only concern is we are breaking compatibility, since people that have the 5.5 version will need to make changed to their `Podfile` in order to keep having the `MapKit` module.
I think a better approach is to release this change with a major version upgrade (i.e. 6.0) and therefore make it clear that this breaks the compatibility (even if a large number of our users are not using the `MapKit` integration, it's still the right way to do it according to the semver standard).

@SDWebImage/collaborators what do you think?

**Comment by dreampiggy** [comment]
Actually...In 6.0.0 I have a bigger idea changes, which want to have a better support for Swift user. Therefore I think we can refactory our architecture with a Swift-written overlay layer (This SDWebImage become the Objc-Swift mixed framework). This is a major changes.

I doubt the break area for users. Because most user basically not integrate MapKit. I do not have a accurate survey, but we can get it through GitHub search with it.

See:

+ Use `SDWebImage/Core` (not with default subspec): https://github.com/search?utf8=%E2%9C%93&q=SDWebImage%2FCore+filename%3APodfile.lock&type=Code&ref=advsearch&l=&l=

image

+ Use `SDWebImage/MapKit`: https://github.com/search?utf8=%E2%9C%93&q=SDWebImage%2FMapKit+filename%3APodfile.lock&type=Code&ref=advsearch&l=&l=

image

**Comment by dreampiggy** [comment]
And, what is `SDWebImage/Main`, did SDWebImage contains any other subspecs in history ?

**Comment by bpoplauschi** [comment]
@dreampiggy the stats you provided are from open source projects. There are many more closed source projects that are using `SDWebImage`.
I don't think we can make the decision based on how many people may or may not be using that submodule. We started years ago to follow the `semver` standard because it has a clear intent of what changes were made in a version and I don't want to bypass it.
Plus, I don't really see why we can't release the `MapKit` removal in a 6.0 version and make all the Swift changes you are referring to in another major version 7.0.

Looking forward to hearing more opinions here, cause I'm not married to my opinion :) and therefore I don't want to force it if more people are against it.

**Comment by dreampiggy** [comment]
Maybe you're right. Actually I don't want to release next major version because currently, seems there are no huge maintain with the exist APIs...The 6.0.0 changes seems source-code compatible for most cases, but all the downstream dependency who use `s.dependency 'SDWebImage', '~> 5.0'` need to bump the version... The pay seems more than what they gain. :(

I'll try to find another SwiftPM DSL, hopelly that can workaround Apple's bug. As the comment in #2941 , seems this effect all the Objective-C project contains 2 or more target...I doubt why so huge bug Apple team does not realize.  :)

**Pull request merged**
