### PR TITLE
Add quary original chche for transformed image

### PR DESCRIPTION
**Pull request by ZXIOU**
Hi, I recently found we didn't implement the use of the original cache，which was used for transformed image.

I read the implementation of **SDWebImageManager** and **SDImageCache** in detail, and found we used **SDWebImageContextOriginalStoreCacheType** to decide how to store original image. By default, **SDWebImageContextOriginalStoreCacheType** is **SDImageCacheTypeNone**, so we will not cache the original image. When we specify caching the original image in memory or on disk or both, we don't have a chance to use it.

For example, if we need some transformed images transformed from the same original image,  we only can  specify how to store the original image , but we will never use it. Everytime I will need to download the same original image.

When the normal cache miss, we can quary cache for original image before downloading. So I do some work to implementation that.

### CODE REVIEW

**Comment by dreampiggy** [comment]
Already exist the implementation: See #2591 

However, the disadvantage of this, is:

When the memory cache hit the original image (but no transformed image), so now, you will "Do transforming code on the main queue"

This is the thing which need consideration.

**Comment by dreampiggy** [comment]
You can do the same thing as below:

```objective-c
@interface SDWebImageDataProvider <SDImageLoader, SDImageCache>

+ (instancetype)dataProviderWithImage:(UIImage *)image data:(NSData *)data;

@end

UIImageView *imageView;
SDWebImageDataProvider *provider = [SDWebImageDataProvider dataProviderWithImage:myImage data:nil];
[sd_setImageWithURL:url options:SDWebImageFromCacheOnly context:[SDWebImageContextImageCache: provider];
```

**Comment by ZXIOU** [comment]
Thank you for your reply, my bro. I'm glad to discuss it with you.

> However, the disadvantage of that behavivoir, is:
> 
> When the memory cache hit the original image (but no transformed image), so now, you will "Do transforming code on the main queue"

For this disadvantage, I think we can easily ensure that these transform operations are implemented in the appropriate asynchronous thread when the main thread is running,  just like the implementation of  ```dispatch_main_async_safe```. And I find transformation processing is really in global queue.

I see #2590 and #2591  in detail, and find that our original intention and idea are basically the same. Now we have merged  #2590,  however #2591 not. So this is still a problem to be solved.

I wanted to use one option named ```SDWebImageTransformAllowQueryFromOriginalCache```(like your ```SDWebImageQueryOriginalAndTransform```)at first，but I found you had implemented the store of original image and  declared ```SDWebImageContextOriginalStoreCacheType``` context to deside how to store. So I declared ```SDWebImageContextOriginalQureyCacheType``` to match this.

As you said：
https://github.com/SDWebImage/SDWebImage/pull/2590#issuecomment-496068331

> > I think `SDWebImageContextStoreCacheType` and `SDWebImageContextOriginalStoreCacheType` are a little misunderstood for users. Have you considered using `SDWebImageOptions`?
> 
> There are 4 behavior for the original image data. If we use the bitcast option, we must at least using two options ?
> 
> * Don't store to cache (default behavior)
> * Store to memory cache only
> * Store to disk cache only
> * Store to both memory cache only
> 
> Or we just do the same thing as Kingfisher. [See here](https://github.com/onevcat/Kingfisher/blob/master/Sources/General/KingfisherOptionsInfo.swift#L174-L180), Which just store it into disk cache, but I don't think it's a good idea, which does not allows the control for store target.

And in my code， I write a separate function named ```callOriginalCacheProcessForOperation:``` for the processing of the original image cache query ranther than in ```callCacheProcessForOperation```.

**Comment by dreampiggy** [comment]
> For this disadvantage, I think we can easily ensure that these transform operations are implemented in the appropriate asynchronous thread when the main thread is running, just like the implementation of dispatch_main_async_safe. And I find transformation processing is really in global queue.

This is OK...But this means, it's no longer **One RunLoop and UIKit will render the placeholder firstly, then replace with your final transformed image**. This will cause a quickly flashback.

**Comment by dreampiggy** [comment]
Can we talk in https://gitter.im/SDWebImage/community ?

**Comment by ZXIOU** [comment]
> > For this disadvantage, I think we can easily ensure that these transform operations are implemented in the appropriate asynchronous thread when the main thread is running, just like the implementation of dispatch_main_async_safe. And I find transformation processing is really in global queue.
> 
> This is OK...But this means, it's no longer **When memory cache hit, all oepration happended in same RunLoop**, which means, UIKit will render the placeholder firstly, then replace with your final transformed image. This will cause a quickly flashback.

OK, I know what you means. Emm..I don't think this will happen， and we can write a test to verify it.

**Comment by ZXIOU** [comment]
> Can we talk in https://gitter.im/SDWebImage/community ?

OK , but I used this for the first time😂😂. Maybe we can communicate in Chinese😂.

**Comment by dreampiggy** [comment]
I'll add test case later.

Current limit:

1. The `.refreshCached` does not get considerated, which means, if we query a image with transformer and ask it to use full image from cache, the all download process will been skipped, no extra HTTP Get. The `.refreshCached` is a issue in current implementation and need to be re-implements. See #2904 
2. The full image always get transformed on global queue, if we hit memory cache, this means the callback is async, may cause a quick flash for user who use it on the tableView/collectionView.

**Comment by ZXIOU** [comment]
@dreampiggy Glad you can merge and we can do better. This problem was discovered by @zhaoguohui, and thank you at the same time.

**Comment by xcodefriend** [comment]
Hello all,

I need to use the cached image in multiple places by resizing the original image to the needed size. The goal is to download the image only ones and use it in all the places.

I have the following setup:
`    
    func setImage(with url: URL?) {
        sd_imageIndicator = SDWebImageActivityIndicator.medium
        sd_imageTransition = .fade

        let resize = SDImageResizingTransformer(size: size, scaleMode: .aspectFill)
        sd_setImage(with: url, placeholderImage: Asset.Images.imageFallback.image,
                    options: [.allowInvalidSSLCertificates, .delayPlaceholder],
                    context: [.imageTransformer: resize,
                              .originalStoreCacheType: SDImageCacheType.disk.rawValue,
                              .originalQueryCacheType: SDImageCacheType.all.rawValue])
    }
`
One thing that I noticed is that if there is no cached image then the image is not fetched from remote. Is this the right behavior or am I missing something?
How can I achieve the desired behavior to download the image only ones and use the resized version where needed?

**Comment by dreampiggy** [comment]
This sounds like a Bug.
If the thumnail cache not hiting, then the full image cache not hiting as well, it should go into the download process.

**Pull request merged**
