### PR TITLE
Refactor APNG and GIF coder implementation

### PR DESCRIPTION
**Pull request by zhongwuzw**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

APNG and GIF typically has the same logical processing, we can extract them to a base class. 
This PR don't contains any breaking, everything works as before.

### CODE REVIEW

**Comment by dreampiggy** [comment]
I don't this use a public abstract class is a good idea. This expose this un-usable class to the public API.

For example, use can use the following code:

```objective-c
SDImageCodersManager.sharedManager.coders = @[SDImageAnimatedCoder.sharedCoder]; // However, this does not work
```

What about using something like a wrapper design, the `SDImageAnimatedCoder` should mark private.

```
@implementation SDImageAPNGCoder

@property (nonatomic, strong) SDImageAnimatedCoder *wrapper; // Internal class, always forward method calls.

@end 

- (instancetype)init {
    self = [super init];
    if (self) {
        self.wrapper = [[SDImageAnimatedCoder alloc] initWithOptions:self.imagePropertyOptions];
    }
    return self;
}

#pragma mark - Decode
- (BOOL)canDecodeFromData:(nullable NSData *)data {
    return [self.wrapper canDecodeFromData:data];
}

- (UIImage *)decodedImageWithData:(NSData *)data options:(nullable SDImageCoderOptions *)options {
    return [self.wrapper decodedImageWithData:data options:options];
}

```

**Comment by bpoplauschi** [comment]
I agree with @dreampiggy. We can either hide this common class behind the 2 existing concrete classes (`APNGCoder` and `GIFCoder`) or just create a single coder that works for both extensions (this later option is to be avoided now, since we don't want to break the backwards compatibility again - we just released a breaking interface 5.0 version).

**Comment by bpoplauschi** [comment]
@zhongwuzw the idea of avoiding code duplication in those 2 coders is very good, we just need a small tweak before we can merge (see above comment).

**Comment by zhongwuzw** [comment]
@bpoplauschi Thanks for advices, I talked about this with @dreampiggy . I can summarize my implementation and how you two guys want.

My implementation:
1. Actually, even if it looks like `GIFCoder` and `APNGCoder` subclass `SDImageAnimatedCoder`, `SDImageAnimatedCoder` is not a real abstract class, we can see the implementations of GIF and APNG coder, both them just call the `init` method of `SDImageAnimatedCoder`, so anyone can use `SDImageAnimatedCoder` directly, create it and use it. 

Two other advices:
**Advice 1**. Use a wrapper to consolidate the code, corder conforms two protocols, it needs to implements 10 protocol methods. Look like below, if you guys think this feels better, I can adopt this implementation.

```
@implementation SDImageAPNGCoder

@property (nonatomic, strong, nonnull) SDImageAnimatedCoder *wrapper; // Internal class, always forward method calls.

@end 

- (instancetype)init {
    self = [super init];
    if (self) {
        self.wrapper = [[SDImageAnimatedCoder alloc] initWithOptions:self.imagePropertyOptions];
    }
    return self;
}

#pragma mark - Decode
- (BOOL)canDecodeFromData:(nullable NSData *)data {
    return [self.wrapper canDecodeFromData:data];
}

- (UIImage *)decodedImageWithData:(NSData *)data options:(nullable SDImageCoderOptions *)options {
    return [self.wrapper decodedImageWithData:data options:options];
}

methodC {
    [wapper methodC]
}
methodD {
    [wapper methodD]
}
...
methodJ {
    [wapper methodJ]
}

```

**Advice 2**. Use message forwarding like `forwardInvocation:` to forward messages dynamic. I don't like this, reasons list:
Because APNG and GIF conforms protocols, if we don't implement protocol methods, we need use some hack way to suppress the warning like `class not conforms the protocol`.
The cost of message forwarding, animated coder methods needs to be called very frequent when render animated images, IMP cache hit not work, always fall back to dynamic. 
So, this way I don't much agree.

@bpoplauschi @dreampiggy If you guys think **Advice 1** is more reasonable, I can change to that.

**Comment by dreampiggy** [comment]
This PR is moved to #2846.

**Pull request closed without merging**
