### PR TITLE
Remove synchronized lock when read cached response from NSURLCache

### PR DESCRIPTION
**Pull request by zhongwuzw**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description
Refer to `Git` log, seems try to fix thread race condition, but actually, this has not any benefit for fix, the reason is read operation would not cause race condition, only if there exist write operation concurrently, only synchronize read operation is useless, we don't do write operation in our framework by ourself, only URL loading system would do it. So if we want to fix race condition, we can't use shared NSURLCache, because we can't control it, and if we use separate NSURLCache for downloader, we may still need to forbidden loading system to store response, instead, we call `storeCachedResponse:forRequest:` by ourself, so we can synchronize read and write operation.

### CODE REVIEW

**Comment by bpoplauschi** [comment]
@zhongwuzw the solution we have on master is a bit weird to me. Based on Apple Docs, the `@synchronized` requires an object to create the lock, not sure what happens when used with a class name like we do `@synchronized(NSURLCache)`, I haven't found similar uses.
But the fact that we don't crash anymore / or the users are not reporting makes me sceptic about removing that code. If you want my opinion, I would just leave it be.

CC @SDWebImage/collaborators

**Comment by zhongwuzw** [comment]
@bpoplauschi I joined in not a long time, so I may missed some discussions. As I [PR description](https://github.com/SDWebImage/SDWebImage/pull/2518#issue-226551689) said, `NSCache` has an inevitable race condition, so if we use `sharedCache` to store and get concurrently, we have no any way to fix it. And why I remove the lock, is we only add lock when we read cache, this is useless, because we don't add lock to write.

**Comment by bpoplauschi** [comment]
@zhongwuzw I agree that we don't lock when writing, so it's pointless. Now I fully understand.
Historically, we kept having crashes due to race condition: some connection was writing data to `NSURLCache` and we were reading `[NSURLCache cachedResponseForRequest:]`.
A big improvement was made in commit e7bd5ab, where we reduced the number of calls to `cachedResponseForRequest`, but that was not a fix. As you said, we can't fix it without locking on the write operation as well as on the read.
I think we could subclass `NSURLCache` and make our own thread safety implementation on top of the `super` methods. Then we can set the it `NSURLCache.sharedURLCache = [OurURLCache new];`. We don't care if there is a different instance passed in via the `session` param.

-----

I said the following, but I was wrong. Poor naming of local ivar with uppercase first letters `URLCache` made me think it was the Swift class name `URLCache`.
> the solution we have on master is a bit weird to me. Based on Apple Docs, the `@synchronized` requires an object to create the lock, not sure what happens when used with a class name like we do `@synchronized(NSURLCache)`, I haven't found similar uses.

**Comment by dreampiggy** [comment]
These code is from #2174. Which is aim to solve the crash in #2156.

Using lock here is actually a hack. We put the `@synchonized()` not on `self`, but on the cache instance. To try our best to make it all access to that `NSCache.sharedCache` inside our framework, is serial.

This is not a 100% fix, but can help to decrease the crash ratio of that case.So I think currently it's no reason to revert back this code.

**Comment by zhongwuzw** [comment]
@bpoplauschi I updated the original code to rename the variable.

> I think we could subclass NSURLCache and make our own thread safety implementation on top of the super methods. Then we can set the it NSURLCache.sharedURLCache = [OurURLCache new];. We don't care if there is a different instance passed in via the session param.

Emm,  we may need to think more a bit, even though fix the race condition is not about this `PR`, I can give some opinions, first, we may careful to set `sharedURLCache`, because all `URLSession` default use this, and also user may use some custom by themself, this option needs to discuss. 

If we want to entirely fix the thread safe, I think the only way is not use `sharedURLCache`(the disadvantage is not shared with users's cache). And maybe use a subclass of `NSURLCache` is an option.

**Comment by bpoplauschi** [comment]
What I had in mind is something like this
```objective-c
@interface SDThreadSafeURLCache()

@property (nonatomic, strong, nonnull) dispatch_queue_t serialQueue;

@end

@implementation SDThreadSafeURLCache

- (instancetype)initWithMemoryCapacity:(NSUInteger)memoryCapacity diskCapacity:(NSUInteger)diskCapacity diskPath:(nullable NSString *)path {
    if (self = [super initWithMemoryCapacity:memoryCapacity diskCapacity:diskCapacity diskPath:path]) {
        _serialQueue = dispatch_queue_create("com.hackemist.SDThreadSafeURLCache", DISPATCH_QUEUE_SERIAL);
    }
    return self;
}

- (nullable NSCachedURLResponse *)cachedResponseForRequest:(NSURLRequest *)request {
    __block NSCachedURLResponse *cachedResponse = nil;
    dispatch_sync(self.serialQueue, ^{
        cachedResponse = [super cachedResponseForRequest:request];
    });
    return cachedResponse;
}

- (void)storeCachedResponse:(NSCachedURLResponse *)cachedResponse forRequest:(NSURLRequest *)request {
    dispatch_sync(self.serialQueue, ^{
        [super storeCachedResponse:cachedResponse forRequest:request];
    });
}

- (void)removeCachedResponseForRequest:(NSURLRequest *)request {
    dispatch_sync(self.serialQueue, ^{
        [super removeCachedResponseForRequest:request];
    });
}

+ (NSString *)defaultCachePath {
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES);
    return [[paths objectAtIndex:0] stringByAppendingPathComponent:@"SDThreadSafeURLCache"];
}
```

and then just make sure we always use that:
```objc
SDWebImageDownloaderOperation
- (nonnull instancetype)initWithRequest:(nullable NSURLRequest *)request
                              inSession:(nullable NSURLSession *)session
                                options:(SDWebImageDownloaderOptions)options
                                context:(nullable SDWebImageContext *)context {
    ...
    if (![NSURLCache.sharedURLCache isMemberOfClass:[SDThreadSafeURLCache class]]) {
        NSURLCache *oldCache = NSURLCache.sharedURLCache;
        NSURLCache.sharedURLCache = [[SDThreadSafeURLCache alloc] initWithMemoryCapacity:oldCache.memoryCapacity diskCapacity:oldCache.diskCapacity diskPath:[SDThreadSafeURLCache defaultCachePath]];
    }
    if (session.configuration.URLCache && ![session.configuration.URLCache isMemberOfClass:[SDThreadSafeURLCache class]]) {
        session.configuration.URLCache = NSURLCache.sharedURLCache;
    }
```

**Comment by zhongwuzw** [comment]
@bpoplauschi 👍 I get your point, use a thread safe NSURLCache is ok, I mean we may need to think wether to replace `NSURLCache.sharedURLCache`, I can list some situations to demonstrate:

1. Users has their own needs, like control disk/memory/diskpath, may create a new instance to replace shared cache(maybe user may use their own subclass of `NSURLCache` to do some custom things). If we just replace by our thread safe NSURLCache, may influence users's needs.
```
    NSURLCache *URLCache = [[NSURLCache alloc] initWithMemoryCapacity:4 * 1024 * 1024
                                                         diskCapacity:32 * 1024 * 1024
                                                             diskPath:@"tmp"];
    [NSURLCache setSharedURLCache:URLCache];
```

2. `NSURLSession` loading system use `defaultSharedCache` to manage cache items, because we changed the diskPath when `SD` work, so if users do some network, maybe they are loading some info from server, this may mess the cached item.

What's your opinion? 🤔

**Comment by dreampiggy** [comment]
```objective-c
NSURLCache.sharedURLCache = [[SDThreadSafeURLCache alloc] initWithMemoryCapacity:oldCache.memoryCapacity diskCapacity:oldCache.diskCapacity diskPath:[SDThreadSafeURLCache defaultCachePath]];
    }
```

This code override the user's default behavior across the Application level. It's like a hook, I'm not recommaned to use this.

The issue seems already been fixed using that lock inside our framework, if user access the shared URLCache, they should have their own way to lock. Instead of we override the Foundation default impelemntation.

**Comment by dreampiggy** [comment]
What is accptable, is that for any `NSURLSessionConfiguration` created inside SDWebImage, you can assign a custom `NSURLCache` subclass. But it's not recommaned to override that `NSCache. sharedURLCache`.

See https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1410148-urlcache?language=objc. You can assign a target cache after URLSession was created.

**Comment by bpoplauschi** [comment]
@dreampiggy the issue is not fixed in our current code, it's only reduced because it's behind the `SDWebImageDownloaderIgnoreCachedResponse` flag.
We only added the synchronization for reading from `NSURLCache`. We can't add it for writing without changing the implementation of `NSURLCache`. The issue is a crash due to a race condition when one thread (network op) is trying to write to `NSURLCache` at the same time our own downloader operation is trying to read.

**Comment by dreampiggy** [comment]
Are there any more crash log like this in the latest firmware (iOS 9.0+) ? I think it's a bug or something that should be handlered by Apple but not developer.

And to solve this, yes, currently we only synchonize the read operation (Seems I don't do that correctly). We can use subclass, but I means you should not touch anything `NSCache.sharedCache`, instead, assign your custom cache class to the `NSURLSessionConfiguration.URLCache`, we can ensure all the URLCache from our framework and synchonized. Directlly assign to `NSCache.sharedCache` will override the Application behavior, which is unacceptable for a framework.

**Comment by dreampiggy** [comment]
I'll have a check at the Fabric or other crash anaylysis tool and give you back the result.

And also, I can help to provide a PR for this. We assign all the `NSURLSessionConfiguration` created inside SDWebImage, using a custom `NSCache` subclass, try to solve this issue.

**Comment by zhongwuzw** [comment]
@bpoplauschi So I think we can merge this `PR` to remove useless lock.

For the thread safe issue, we all agree to use a lock to protect race condition, @bpoplauschi already post the [code](https://github.com/SDWebImage/SDWebImage/pull/2518#issuecomment-437973735),   and small optimize is using `read-write` lock, this may best fit.

Another is we can assign a singleton `SDThreadSafeURLCache` for our default `URLCache`, not one session one `SDThreadSafeURLCache` instance.

**Comment by dreampiggy** [comment]
@zhongwuzw I actually means like this:


```objective-c
//SDWebImageDownloade.m :120
NSURLSessionConfiguration *sessionConfiguration = _config.sessionConfiguration;
if (!sessionConfiguration) {
    sessionConfiguration = [NSURLSessionConfiguration defaultSessionConfiguration];
}
sessionConfiguration.URLCache = SDThreadSafeURLCache.sharedCache;
```

**Comment by zhongwuzw** [comment]
@dreampiggy I prefer option two, provide an opportunity for user for custom, if they do, they need take care of race condition by themself.

**Comment by zhongwuzw** [comment]
A long time to fix.

**Comment by zhongwuzw** [comment]
@dreampiggy Do you still have any considerations?

**Pull request closed without merging**
