### PR TITLE
 Shorten code indentation

### PR DESCRIPTION
**Pull request by huangboju**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

Shorten code indentation and improve readability

### CODE REVIEW

**Comment by dreampiggy** [comment]
Seems...Just code indent and style fix ?

**Comment by huangboju** [comment]
Yes

**Comment by bpoplauschi** [comment]
@huangboju you should take a look at the build failure and fix that :) thanks for your contribution

**Review by dreampiggy — APPROVED** [review]

**Comment by bpoplauschi** [comment]
@dreampiggy the build was failing for this PR. Is it unrelated to those changes?

**Comment by dreampiggy** [comment]
Not the case. The current master branch test case not so solid on some test case (because of bad URL used in our test case).

**Comment by dreampiggy** [comment]
Current latest success: https://travis-ci.org/github/SDWebImage/SDWebImage/builds/745171559?utm_source=github_status&utm_medium=notification

**Pull request merged**
