### PR TITLE
Fix rounded corner bug which leads to image upside down

### PR DESCRIPTION
**Pull request by zhongwuzw**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

We mix use CG functions and UIKit functions, leads image upside down. This bug can leads all images upside down when users use `SDImageRoundCornerTransformer` or use `sd_roundedCornerImageWithRadius` directly.

### CODE REVIEW

**Comment by dreampiggy** [comment]
Confirmed. Seems a bug that escaped from the test case. Because our test image, looks like this:

image

And after apply the rounded coder in test case : `test03UIImageTransformRoundedCorner`, it looks OK because the unside-down changes does not cause anything strange. 😅 

Your fix is OK. Actually, this code is original from [YYCategories](https://github.com/ibireme/YYCategories/blob/master/YYCategories/UIKit/UIImage%2BYYAdd.m#L369-L417). But at that time due to the macOS compatible changes, introduce this issue.

**Comment by dreampiggy** [comment]
What about update the test cases as well ? Using another image (not have any symmetry). And then, using the `sd_colorAtPoint:` to check the pixel color to avoid this stupid bug in the future.

**Comment by dreampiggy** [comment]
This issue apply to iOS only, not macOS. Since the Core Graphics coordinate system is the same as AppKit.

**Comment by zhongwuzw** [comment]
@dreampiggy I'll add test.

**Comment by dreampiggy** [comment]
@zhongwuzw I means...Use another image, which is not symmetry. (Upside-down look the same).

For example, use `TestImage.jpg` or something, for this rounded corner test.

Or maybe we can replace all exisiting test cases with a more random images, like the famous [Lena.png](http://optipng.sourceforge.net/pngtech/img/lena.html)

**Comment by zhongwuzw** [comment]
image

**Pull request merged**
