### PR TITLE
Added xcprivacy manifest to CocoaPods

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

Using the resource bundle syntax

See: https://github.com/CocoaPods/CocoaPods/issues/10325

Should work when using CocoaPods with `use_frameworks! :linkage => what_ever`

### CODE REVIEW

**Comment by rafaelnobrekz** [comment]
@dreampiggy SDWebImage 5.19.1 from CP does not seem to include the privacy info file in the project, neither ship it in the bundled framework 🤔 
Screenshot 2024-05-07 at 12 09 12
Screenshot 2024-05-07 at 12 09 53

**Comment by rafaelnobrekz** [comment]
I just realized what's wrong here. The app was only indirectly fetching SDWebImage/Core, not the full podspec. Thus the resources folder was missing.

**Comment by dreampiggy** [comment]
> I just realized what's wrong here. The app was only indirectly fetching SDWebImage/Core, not the full podspec. Thus the resources folder was missing.

Seems CocoaPods bug... It ignore the root spec resource bundle...

**Comment by dreampiggy** [comment]
I can move this into SDWebImage/Core ?

**Comment by dreampiggy** [comment]
Acutally, if you use pod "SDWebImage", it actually integrates only "SDWebImage/Core" and the resource bundle contains privacy file

**Comment by rafaelnobrekz** [comment]
This is the diff from the previous setup (indirectly adding SDWebImage) and the one where CP does add the Privacy resource. Not sure if it's a CP bug or expected behavior, as the lib require only the Core subspec

Screenshot 2024-05-07 at 12 28 17

**Pull request merged**
