### PR TITLE
Fix `imageIndicator` retain cycle issue, and avoid leak

### PR DESCRIPTION
**Pull request by kinarob**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description

 Fix `imageIndicator` in combinedProgressBlock has retain cycle issue.

### CODE REVIEW

**Comment by dreampiggy** [comment]
Retain cycle ? Which object did `imageIndicator` retained ? Did I miss something ?

self -> imageIndicator -> End
self -> progressBlock -> imageIndicator -> End

**Comment by bpoplauschi** [comment]
@kinarob can you detail how you found the cycle? What is using the Xcode inspectors?

**Comment by kinarob** [comment]
I have a deeply look in this code, As @dreampiggy said:
self -> imageIndicator -> End
self -> progressBlock -> imageIndicator -> End
I also have a try with `FBRetainCycleDetector`,  It' s ok. Maybe I was wrong about something, I will careful next time. Thanks guys have a look, I will close it.

**Comment by dreampiggy** [comment]
Be free to report the issue. There may be some mistake in code and issue can help us to find it.

Tips: Xcode has a really powerful memory graph tool to show all alive objects in the memory. And there will be a purple exclamation mark on that object. You can open it up at any time via the toolbar (next to the pause breakpoint button). It’s really easy to find whether there are retain cycle or not.

**Comment by kinarob** [comment]
@dreampiggy You are right. I will follow you advice, Thank you!

**Pull request closed without merging**
