### PR TITLE
Avoid cancel same image loading in same View instance

### PR DESCRIPTION
**Pull request by mTz0206**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description
https://github.com/SDWebImage/SDWebImage/issues/3568

### CODE REVIEW

**Comment by dreampiggy** [comment]
Looks OK on `UIImageView` that category support.

But...Maybe need a way to workaround `UIButton` (Called, multi-state-image-view)...Which will cause issue in current `sd_imageURL` design because it does not associated to a `State`

I write a implmentation 2 years ago but has no response, which is ugly and hacky... https://github.com/SDWebImage/SDWebImage/pull/2790

**Comment by mTz0206** [comment]
> Looks OK on `UIImageView` that category support.
> 
> But...Maybe need a way to workaround `UIButton` (Called, multi-state-image-view)...Which will cause issue in current `sd_imageURL` API, because it does not associated to a `State`. Actually I try to avoid touching that property
> 
> I write a implementation 2 years ago but has no response, which is ugly and hacky so I close it and forgot that... #2790
> 
> image
> 
> image

oh @dreampiggy, thanks for your review and let me try to understand what is your point, do you mean the view who can be set multiple images, when we try to load images for different state at the same time, in current sd_internalSetImageWithURL function, the multiple image loading operation will canceled each other, this is what you want to fix right?

**Comment by dreampiggy** [comment]
> this is what you want to fix right?

I don't want to fix this, but if user use UIButton, you new code will cause `More problems for them`, make things worse.

But I don't think it's your duty to fix this bad design about UIButton in this PR.

**Comment by dreampiggy** [comment]
A better idea is to mark some warning in `UIButton+WebCache`, or `UIImage+Highlighted`

**Comment by mTz0206** [comment]
@dreampiggy 

1. > I don't want to fix this, but if user use UIButton, your new code will cause More problems for them than previous, make things worse (It's bad enough currently).
     - I don't understand why the new code will cause more problems? I think it should be same as now. can you explain more?

2. and I also review the code for the `multi-state-image-view` case. 
  - I think the maybe SDWebImageContext could resolve it.
  - because current operation's management is base on `    NSString *validOperationKey = context[SDWebImageContextSetImageOperationKey];
` actually user can customize the key for each status, so if we want make it more convenient for usage, we could add some default customize key  for UIButton+WebCache, or UIImageView+Highlighted. right?

**Comment by dreampiggy** [comment]
> actually user can customize the key for each status

No, this is not designed as public API, only for SD's third-party integration (like that FirebaseStorageUI integration) to use.

**Comment by dreampiggy** [comment]
> I don't understand why the new code will cause more problems? I think it should be same as now. can you explain more?

Previously, this:

1. `UIButton setImageWithURL:url1 forState:normal`
2. `UIButton setImageWithURL:url1 forState:touchUpInside`
Will still work and set the images into that UIButon's 2 states

However, after you changes, since `UIButton.sd_imageURL` is memorized

Will cause that UIButton's touchUpInside no longer set any image, and will cause blank when user touch.


It's already buggy, but this new `behavior changes` make more buggy...

But this is SDWebImage's old design issue, not your duty. If you want to merge, maybe I have to pick up #2790 and merge it before your PR merged in

**Comment by dreampiggy** [comment]
You can guess what I means, that `UIView. sd_imageURL` is **Deprecated and dangerous API which I don't recommended anyone to use, for now**

Until I provide new API like `UIView sd_imageURLWithKey:`

**Comment by mTz0206** [comment]
> > actually user can customize the key for each status
> 
> No, this is not designed as public API, only for SD's third-party integration (like that FirebaseStorageUI integration) to use.
oh this is what I mean. 
```
        button.sd_setImage(with: URL(string: "https://xx"),
                                  for: .normal,
                                  placeholderImage: nil,
                                  context: [SDWebImageContextOption.setImageOperationKey : "normal"],
                                  progress: nil, completed: nil)
        button.sd_setImage(with: URL(string: "https://xx"),
                                  for: .highlighted,
                                  placeholderImage: nil,
                                  context: [SDWebImageContextOption.setImageOperationKey : "highlighted"],
                                  progress: nil, completed: nil)
```
it could help to avoid image loading canceled right?
and of course like your sample code, my code could impact original logic.

**Comment by dreampiggy** [comment]
That `setImageKey` is used to define `Which KeyPath you want your image to set`

Means, it can be a `KeyPath: \.image, \.highlitedImage, \.normalState \.touchUpInsideState`

It's not URL or Cache Key

This is history bad design for multi-state-image-view.

So, you shoud not rely on `Anything not bind with setImageKey` to do cancel.

If I provide the API like `sd_imageURLForSetImageKey: key`, then you can say that current request can be cancelled safely because URL are same

**Comment by dreampiggy** [comment]
In SD 6.0, I decide to provide new API for Swift user to always pass `KeyPath`, defaults to `\UIImageView.image` for `UIImageView.sd.setImage(with: url)`

**Comment by dreampiggy** [comment]
@mTz0206 See #3576 

You need the new API from that and then merge-in.

**Comment by dreampiggy** [comment]
Any update ? Do we still need this PR

I suggest to add a new option (to not cancel current loaded image request)

**Comment by mTz0206** [comment]
> Any update ? Do we still need this PR ?
> 
> I suggest to add a new option (to not cancel current loaded image request)

thanks, I will review this  > See https://github.com/SDWebImage/SDWebImage/pull/3576
and try it this weekend, thank you still remember this.

**Comment by dreampiggy** [comment]
I can provide a draft PR for you actually. Check if this match your feature request.

**Comment by mTz0206** [comment]
> I can provide a draft PR for you actually. Check if this match your feature request.

oh really？ thank for that.

**Comment by dreampiggy** [comment]
See #3592's test case about the new behavior. I guess this is enough for you ?

By the way, I think in the more complicated scenario, you can directly call `SDWebImageManager` instead of use the built-in logic from `UIView+WebCache.m`

**Pull request closed without merging**
