### PR TITLE
Declare SDWebImageDownloaderOptions no options

### PR DESCRIPTION
**Pull request by iliaskarim**
### New Pull Request Checklist 

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

### Pull Request Description

This named value is more descriptive than a `0` in calls to `-downloadImageWithURL:options:progress:completed:`.

### CODE REVIEW

**Comment by zhongwuzw** [comment]
@iliaskarim Thanks for your `PR`! I can give my thoughts, maybe I think it may not have any benefit, because `SDWebImageDownloaderNoOptions` don't represent any default value, we can see how `Apple` does like below, `UIViewAnimationOptionCurveEaseInOut`,`UIViewAnimationOptionTransitionNone ` both equal to `0`, means default value, and it has specific implication. So we may just don't need to add `SDWebImageDownloaderNoOptions`.

```
    UIViewAnimationOptionLayoutSubviews            = 1 <<  0,
    UIViewAnimationOptionAllowUserInteraction      = 1 <<  1, // turn on user interaction while animating
    UIViewAnimationOptionBeginFromCurrentState     = 1 <<  2, // start all views from current value, not initial value
    UIViewAnimationOptionRepeat                    = 1 <<  3, // repeat animation indefinitely
    UIViewAnimationOptionAutoreverse               = 1 <<  4, // if repeat, run animation back and forth
    UIViewAnimationOptionOverrideInheritedDuration = 1 <<  5, // ignore nested duration
    UIViewAnimationOptionOverrideInheritedCurve    = 1 <<  6, // ignore nested curve
    UIViewAnimationOptionAllowAnimatedContent      = 1 <<  7, // animate contents (applies to transitions only)
    UIViewAnimationOptionShowHideTransitionViews   = 1 <<  8, // flip to/from hidden state instead of adding/removing
    UIViewAnimationOptionOverrideInheritedOptions  = 1 <<  9, // do not inherit any options or animation type
    
    UIViewAnimationOptionCurveEaseInOut            = 0 << 16, // default
    UIViewAnimationOptionCurveEaseIn               = 1 << 16,
    UIViewAnimationOptionCurveEaseOut              = 2 << 16,
    UIViewAnimationOptionCurveLinear               = 3 << 16,
    
    UIViewAnimationOptionTransitionNone            = 0 << 20, // default
    UIViewAnimationOptionTransitionFlipFromLeft    = 1 << 20,
    UIViewAnimationOptionTransitionFlipFromRight   = 2 << 20,
    UIViewAnimationOptionTransitionCurlUp          = 3 << 20,
    UIViewAnimationOptionTransitionCurlDown        = 4 << 20,
    UIViewAnimationOptionTransitionCrossDissolve   = 5 << 20,
    UIViewAnimationOptionTransitionFlipFromTop     = 6 << 20,
    UIViewAnimationOptionTransitionFlipFromBottom  = 7 << 20,
```

**Comment by dreampiggy** [comment]
This enum have no extra meaning. And it's totally been ignored by Swift user. You just need to pass `[]`.

**Comment by iliaskarim** [comment]
You're correct @zhongwuzw that there is not necessarily a need to add this default value name so much as it is a nicety that improves the interface for client programmers much like the Apple example you provided. An engineer would either be able to pass `0` as `UIViewAnimationOptionLayout` which would then a reader of that code would have to look up via the enum declaration/documentation, or the original engineer could pass the combination of `UIViewAnimationOptionLayoutSubviews`, `UIViewAnimationOptionCurveEaseInOut` and `UIViewAnimationOptionTransitionNone` for future readers of the code to see or even better to future proof the code in case the default values change. In this case as multiple values are set, all of which are 0, and to avoid the use of excessive boilerplate, a convenience method can be declared that provides these default values.

@dreampiggy this PR is intended to improve the objective-c interface by changing a the sentinel value `0` into a human readable text description.

We can see both from the Apple enum posted above and from UIViewAutoresizing that the established convention in objective-c is in to provide a name for the default setting of an enum just as in the .
```
typedef NS_OPTIONS(NSUInteger, UIViewAutoresizing) {
        UIViewAutoresizingNone                 = 0,
        UIViewAutoresizingFlexibleLeftMargin   = 1 << 0,
        UIViewAutoresizingFlexibleWidth        = 1 << 1,
        UIViewAutoresizingFlexibleRightMargin  = 1 << 2,
        UIViewAutoresizingFlexibleTopMargin    = 1 << 3,
        UIViewAutoresizingFlexibleHeight       = 1 << 4,
        UIViewAutoresizingFlexibleBottomMargin = 1 << 5
};  
```
This convention improves code readability.

A further improvement would be to prefix all of the enum value names with the same prefix as is also established objective-c convention.

**Comment by zhongwuzw** [comment]
@iliaskarim `UIViewAutoresizingNone` actually has specific meanings, it means don't do autoresizing. For this `PR`, at least `SDWebImageDownloaderNoOptions` has not any meaning, so we can't import this IMO, I think we have two options, one is add all default options like `UIViewAnimationOption`, another is keep the original.

**Comment by iliaskarim** [comment]
That's perfectly clear @zhongwuzw. I understand. Both options seem good but for clarities sake the first that you suggested, to add all default options to `SDWebImageDownloaderOptions` like `UIViewAnimationOption` seems clearest for users.

Another idea is how about a convenience interface? E.g.
```
- (nullable SDWebImageDownloadToken *)downloadImageWithURL:(nullable NSURL *)url
                                                 completed:(nullable SDWebImageDownloaderCompletedBlock)completedBlock;
```
because progressive download is disabled by default, we can omit the progress block parameter.

**Comment by zhongwuzw** [comment]
@iliaskarim Provide convenience interfaces just like `UIImageView+WebCache` `setImage` method is reasonable for me, @SDWebImage/collaborators any opinions?

**Comment by zhongwuzw** [comment]
Closing in favor of #2633 .

**Pull request closed without merging**
