### PR TITLE
simplify assign downloaderOperation's minimumProgressInterval code

### PR DESCRIPTION
**Pull request by Insofan**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description
Simplify assign downloaderOperation's minimumProgressInterval code, had passed by my repo travis ci.

### CODE REVIEW

**Comment by Insofan** [comment]
@dreampiggy Why SD ci says failed. I have test this code on my repo's travis and  it passed.How to save this pr travis build?

**Comment by dreampiggy** [comment]
@Insofan Our Travis-CI build script, now always using the latest version of CocoaPods (including the beta version), and I guess some test case have thread-safe issue to cause the test case crahsed. I'll try to investigate and fix it.

Current, you can do a travis-CI retry after you login the Travis-CI.org with GitHub account. If you can not restart the test, try to ammend a empty change commit and force push to your remote branch, this will trigger the retry.

**Comment by Insofan** [comment]
> @Insofan Our Travis-CI build script, now always using the latest version of CocoaPods (including the beta version), and I guess some test case have thread-safe issue to cause the test case crahsed. I'll try to investigate and fix it.
> 
> Current, you can do a travis-CI retry after you login the Travis-CI.org with GitHub account. If you can not restart the test, try to ammend a empty change commit and force push to your remote branch, this will trigger the retry.

This pr has passed.I didn't find  restart trigger on SD's travis, maybe I don't have the permission. I know how to restart my fork repo's travis. Recently I'm reading the source code, I'll investigate this part too.

**Comment by dreampiggy** [comment]
@Insofan We’ll release the last 5.0.0 beta(beta6). The merge from master branch to 5.x will be done by me periodicity. You don’t have to do so.

After we finally want to release 5.0.0, we will follow the steps and merge 5.x branch to master. The current master will become another 4.x branch to keep a short-term maintain branch for serious bug in 4.x version.

**Pull request merged**
