### PR TITLE
fix Xcode 11 warnings

### PR DESCRIPTION
**Pull request by dvshelley**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

...

### CODE REVIEW

**Comment by bpoplauschi** [comment]
@dvshelley thanks for taking the time to create this PR, I think it's valuable.
I do have a few comments: first of all, the target branch is `3.x` which is a very old branch of ours, you should be targeting the `master` branch.
Also, please note most of our settings are in `xcconfig` files, so you would need to make those changes there instead of the `xcodeproj` where they just duplicate and are hard to review.

**Comment by dreampiggy** [comment]
There are no any warning in the master branch. Our all CI and local environment already use Xcode 11...
Maybe it’s only something reletaed to SD 3.x

**Comment by dvshelley** [comment]
This PR only applies to the 3.x branch. We still use it for our app.
The 3.x branch doesn't use xcconfig files.
I don't think that the build checks are compatible with the 3.x branch, which is causing them to fail.

**Comment by bpoplauschi** [comment]
@dvshelley sorry, I din't think you were indeed targeting the 3.x branch.
You're right about the build script, but we could bypass those and force merge.
The question is: do you also need a 3.x release with Xcode 11 support? Could we just use the 3.x branch as it is?

**Comment by dvshelley** [comment]
Yes please. Adding Xcode 11 support to the 3.x branch would be good. This PR fixes a handful of annoying warnings that Xcode 11 introduces - language file setup, new for Xcode 11 project checks. I'm sorry, I should have provided more detail in my PR.

**Comment by dvshelley** [comment]
@bpoplauschi Yes, please merge this for Xcode 11 support for the 3.x branch.

**Comment by dreampiggy** [comment]
It's OK I think. Since we does not maintain the 3.x branch totally.
These changes only effect some warning flags, but not the logic, maybe this is helpful for those users. I'll merge that.

**Comment by dvshelley** [comment]
Thanks! @dreampiggy

**Pull request merged**
