### PR TITLE
Prioritize SDWebImageDownloaderHighPriority if operation already exists

### PR DESCRIPTION
**Pull request by jerelevine**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description

...

### CODE REVIEW

**Comment by dreampiggy** [comment]
This seems need more consideration. Could you please provide your use case with more detail information and let me understand why you need this ?

`NSOperationQueuePriority`, according to Apple's doc and practice, it used to specify the priority for pending operation, inside `NSOperationQueue`. Which one should be firstlly beeen executed. It does no effect if the operation is already started. See [queuePriority](https://developer.apple.com/documentation/foundation/nsoperation/1411204-queuepriority)

>  This value is used to influence the order in which operations are dequeued and executed.

So, from our current logic, if we queried a operation from the downloader, it must be a operation which already started (means the `main` method is called). It does not effect to do this.

If you means to optimise the QoS or something, the current implementation does already do this.

**Comment by jerelevine** [comment]
Thanks for responding! First, let me describe my use-case. I prefetch (with a low priority) a server page of image urls (approximately 20). And then as a user scrolls, I fetch the image urls (with a high priority) that correspond to the data onscreen. I want the onscreen images to get high priority even if I've already started to prefetch them.

> It does no effect if the operation is already started.
That is the case but just because the operation exists, doesn't mean it's been started. If I check the `operation.isExecuting` where this priority is set, the values are not always `YES`. The operation was added to the queue but it hasn't started executing yet.

See [nshipster](https://nshipster.com/nsoperation/).
> To kick off an NSOperation, either call start, or add it to an NSOperationQueue, to have it start once it reaches the front of the queue. 

So the operation can be added to the operation queue without it having been started or the `main` method being called.

**Comment by jerelevine** [comment]
Thoughts on my commment?

**Comment by dreampiggy** [comment]
@jerelevine I understand your use case. Seems this is a better approach to let that `SDWebImageDownloaderHighPriority` works for more appropriate situation.

One suggestion, since this is a non-API break change, we can fix it in 4.x as well as 5.x. And I think we can also treat `SDWebImageDownloaderLowPriority` as well.

**Comment by dreampiggy** [comment]
@jerelevine See #2562. Which is more robust code. If we want to merge, firstly merge that into master, then we can directly merge back to 5.x.

**Comment by dreampiggy** [comment]
This is fixed by #2575. It's available in SDWebImage 4.4.4 version. Thanks for your contribution. 😄

**Pull request closed without merging**
