### PR TITLE
The length of some special long pathExtension + 32(md5) could exceed the Maximum length(256) of filename specified by the system.

### PR DESCRIPTION
**Pull request by yjh1313**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / reffers to the following issues: ...

### Pull Request Description

...

https://imggen.alicdn.com/3b11cea896a9438329d85abfb07b30a8.jpg?aid=tanx&tid=1166&m=%7B%22img_url%22%3A%22https%3A%2F%2Fgma.alicdn.com%2Fbao%2Fuploaded%2Fi4%2F1695306010722305097%2FTB2S2KjkHtlpuFjSspoXXbcDpXa_%21%210-saturn_solar.jpg_sum.jpg%22%2C%22title%22%3A%22%E6%A4%8D%E7%89%A9%E8%94%B7%E8%96%87%E7%8E%AB%E7%91%B0%E8%8A%B1%22%2C%22promot_name%22%3A%22%22%2C%22itemid%22%3A%22546038044448%22%7D&e=cb88dab197bfaa19804f6ec796ca906dab536b88fe6d4475795c7ee661a7ede1&size=640x246

### CODE REVIEW

**Comment by bpoplauschi** [comment]
@yjh1313 did you try running the tests locally?

**Comment by yjh1313** [comment]
@bpoplauschi yeah，The tests run normally.

**Comment by dreampiggy** [comment]
Emmm...Actually the demo url, provided by you, will not limit the max length of file name. Because the extension name is `.jpg`, but not something like `.jpg%22%2C%22title%22%3A%22%E6%A4%8D%E7%89%A9%E8%94%B7%E8%96%87%E7%8E%AB%E7%91%B0%E8%8A%B1%22%2C%22promot_name%22%3A%22%22%2C%22itemid%22%3A%22546038044448%22%7D&e=cb88dab197bfaa19804f6ec796ca906dab536b88fe6d4475795c7ee661a7ede1&size=640x246`

This is break-usage changes for current SDWebImage version, because you change the algorithm for generating the disk cache file name. It should be considered carefully.

In my opinion, the `extension` name, should not contains all the extra params from URL, for this URL, it should be treated as `.jpg` . So current file name behavior is correct, and since the `extension` name will never be larger than 255. So it's OK.

**Comment by bpoplauschi** [comment]
Guys, what is the action to take here? Just close this PR?
@zhongwuzw @mythodeia @skyline75489 what do you think?

**Comment by zhongwuzw** [comment]
Emm, in theory, it maybe has, but in reality, maybe no needed to handle this situation IMO, it's hardly or never occur.

**Comment by dreampiggy** [comment]
@zhongwuzw The reality, is that we use `NSURL.pathExtension` to determine the path of url. So it should not contains anything such as that `%22%2C%22title%22%3A%22%E6%A4%8D%E7%89%A9%E8%94%B7%E8%96%87%E7%8E%AB%E7%91%B0%E8%8A%B1%22%2C%22promot_name%22%3A%22%22%2C%22itemid%22%3A%22546038044448%22%7D&e=cb88dab197bfaa19804f6ec796ca906dab536b88fe6d4475795c7ee661a7ede1&size=640x246`. The extension should only be `jpg`.

You can run a demo to trigger a test. So this is why I wait for @yjh1313 's response about it.

**Comment by zhongwuzw** [comment]
@dreampiggy Emm, what's the difference of my comment and your explanation? 🤔 

In reality, there hardly has a much long `pathExtension`, but it can, we use `url` as the cache key by default, `url`'s length (some browser limit 1024) can be longer than file's max length in disk, so `pathExtension` also can exceed 254, just like my comment above, the theory is exist, but actually it rare.

```
https://imggen.alicdn.com/3b11cea896a9438329d85abfb07b30a8.jpgasaaaaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjaaaaaaaaaaaaaaaaajjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
```

**Comment by zhongwuzw** [comment]
Needs discussion.

**Comment by bpoplauschi** [comment]
Agree with @dreampiggy

**Comment by bpoplauschi** [comment]
I don't see GitHub activity for a long period on @yjh1313 account - we might need to do the changes on our own :)

**Comment by zhongwuzw** [comment]
@bpoplauschi 👌 I'll finish it.

**Comment by bpoplauschi** [comment]
Replaced by #2516 - closing

**Pull request closed without merging**
