### PR TITLE
Add support for Swift Package Manager

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/) // Will Add some wiki in [Installation-Guide](https://github.com/SDWebImage/SDWebImage/wiki/Installation-Guide) part, if this been merged.
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: #2751

### Pull Request Description

Xcode 11 introduce the support for Swift Package Manager (SwiftPM). Today I check the SwiftPM's documentation, it supports for not only Swift files, but also the C/C++ files.

So, since SDWebImage is written in Objective-C, it should be supported. And I did this. The `Package.swift` is like the `Podfile`, a rule to define the compile and target. See the full documentation for [Package.swift syntax](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md)

See the screenshot for usage under Xcode 11 Beta, and using [Accio](https://github.com/JamitLabs/Accio) to integrate with iOS project target.

#### Swift Build (Generate Some Obj files and .a .dylib)
image

#### Accio Install
image

#### SwiftPM Dependency
image

#### Build
image

### CODE REVIEW

**Comment by dreampiggy** [comment]
@OkiRules

**Comment by bpoplauschi** [comment]
Nice job @dreampiggy, I will take a closer look at this, but the first impression is a good one :)

**Comment by OkiRules** [comment]
Thanks @dreampiggy and @bpoplauschi! Looking forward to this update!

**Comment by daveanderson** [comment]
I just hacked together basic Swift Package Manager support (not as clean as this) and then discovered this variation. Can't wait for it to land.

**Comment by dreampiggy** [comment]
Since #2761 is merged. Now this PR can be passed.

Note because of the limitation of SwiftPM `Package.swift` syntax in Swift 4.2 (does not support cSettings), we have to use Swift 5 syntax.

**Comment by bpoplauschi** [comment]
I think this looks good and will help people who want to use SPM. Any blockers for a merge?

**Comment by dreampiggy** [comment]
@bpoplauschi Nothing. I'll merge it now.

**Pull request merged**
