### PR TITLE
Refactoring the memory cache to LRU algorithm replacement

### PR DESCRIPTION
**Pull request by Insofan**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description
Change the memory cache to LRU algorithm.
I'm confusing with two point
#### 1. The original iOS/tvOS memory cache logic based on NSMapTable, after disable weakMap option, all memory cache depend on NSCache. This comment 

> Current this seems no use on macOS (macOS use virtual memory and do not clear cache when memory warning). So we only override on iOS/tvOS platform.

I'm not familiar with macOS. I think after refactoring, all platform could use LRU algorithm and this pr I haven't change it. 

#### 2. Should I set a default value to max cache memory limit or count. Now default value is "no limit".

BTW:
If this logic approve. Should I divide LRU implementation to several file, when I'm coding this implementation is under 5.0 beta6 version.

### CODE REVIEW

**Comment by Insofan** [comment]
@dreampiggy This pr rebase the SD latest 5.x branch. Plz review it.

**Comment by dreampiggy** [comment]
Seems something need to do before detail code reviewing.

1. Could you please change the base branch to `master`.
`5.x` is now out-of-date after 5.0 release. It will be deleted. So just using the `master` branch

2. Is this feature ready for 5.0 or 6.0 ? 
Seems there are some API breaking in public APIs in the PR. If you desired to do so, maybe we can add this to 6.0.0 milestone. Or, you need to polish the API to not breaking any exisiting public APIs.

We following the sem-version, see: https://semver.org/

**Comment by Insofan** [comment]
@dreampiggy Em... I have read sem-ver.According to sem-ver rules, I wanna add this feature into 5.1.0 version and provide a memory cache option enumeration(fifo, lru...) in 6.0 ver. How about add a shouldUseLRUMemoryCache property(do not break any exit public api) to SDImageCacheConfig class in 5.1.0 version. There are three memory cache implementations, NSCache, NSMapTable, LRU, make weakMap as default.If trigger LRU option using lru algorithm. And LRU code still in SDMemoryCache class or add another abstract class.

**Comment by dreampiggy** [comment]
@Insofan `5.x` branch is removed because we already release 5.0. Please change the base branch to `master` to ready for future review.

**Comment by Insofan** [comment]
@dreampiggy Fine

**Comment by Insofan** [comment]
refresh

**Comment by dreampiggy** [comment]
@Insofan Hi. Are you still active ?
I think this PR again. I have another idea. What about writing two class, one keep current `SDMemoryCache`, renaming to `SDMemoryNSCache` or something. Then another is your new cache, `SDMemoryLRUCache`.

We place a new config like this `shouldUseLRUCache` on `SDImageConfig` property, defaults to NO (To keep potential backward compatible ?, can be discussed)

Then, our `SDMemoryCache` become a base abstract class, it will proxy all the call to whether `SDMemoryNSCache` or `SDMemoryLRUCache`. Which is transparent to the users. 

The `SDMemoryNSCache` and `SDMemoryLRUCache` can be implementation detail and keep in private class. This can make us flexible to change the detail implementation. Also this time you don't need to write complicated check code in implementation (like your current `_nsCache` check)

**Comment by dreampiggy** [comment]
```objective-c
// Private
@interface SDMemoryNSCache : NSCache
@end

// Private
@interface SDMemoryLRUCache : NSObject
@end

// Public
@interface SDMemoryCache <KeyType, ObjectType> : NSCache <KeyType, ObjectType> <SDMemoryCache>
@end

@implementation SDMemoryCache
- (id)objectForKey:(id)key {
    if (self.config.shouldUseLRUCache) {
        return [self.LRUCache objectForKey:key];
    } else {
        return [self.NSCache objectForKey:key];
    }
}
@end
```

**Comment by dreampiggy** [comment]
And. I think this PR is great if we have a full performance test between NSCache and LRU Cache. Could you please help to provide one ?

You can run local test code in a demo running on real device, test the query speed and storage speed for random access, also with some sequence access, etc.

**Comment by Insofan** [comment]
@dreampiggy Yeah, if you think it's better I'll rewrite it then pr.

**Comment by dreampiggy** [comment]
@Insofan And you can totally ignore that `weak cache` algorithm in your LRU implementation. Just forcus on LRU node, don't consider the weak map table.

This weak cache should  be a seperate part besides the memory cache class implementation, I'll do a refactory for this.

**Comment by Insofan** [comment]
@dreampiggy replaced by new pr  #2766

**Pull request closed without merging**
