### PR TITLE
Try to solve the strange dispatch group crash in SDSafeExecute by removing inline

### LINKED ISSUE #3512: 5.15.5 [SDCallbackQueue async:] 崩溃
使用 5.15.5 版本，Bugly后台出现了`[SDCallbackQueue async:] ` 相关的崩溃，堆栈信息如下

```
#0 Thread

SIGSEGV

SEGV_ACCERR

解析原始
0
libobjc.A.dylib
_objc_release + 24
1
2d_noSuper_education
-[SDCallbackQueue async:] (SDCallbackQueue.m:0)
2
2d_noSuper_education
-[SDCallbackQueue async:] (SDCallbackQueue.m:0)
3
2d_noSuper_education
-[SDWebImageManager callCompletionBlockForOperation:completion:image:data:error:cacheType:finished:queue:url:] (SDWebImageManager.m:685)
4
2d_noSuper_education
-[SDWebImageManager callCompletionBlockForOperation:completion:error:queue:url:] (SDWebImageManager.m:673)
5
2d_noSuper_education
__125-[SDWebImageManager callDownloadProcessForOperation:url:options:context:cachedImage:cachedData:cacheType:progress:completed:]_block_invoke (SDWebImageManager.m:0)
6
libdispatch.dylib
__dispatch_call_block_and_release + 24
7
libdispatch.dylib
__dispatch_client_callout + 16
8
libdispatch.dylib
__dispatch_main_queue_callback_4CF$VARIANT$mp + 1068
9
CoreFoundation
___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
10
CoreFoundation
___CFRunLoopRun + 1924
11
CoreFoundation
_CFRunLoopRunSpecific + 436
12
GraphicsServices
_GSEventRunModal + 104
13
UIKitCore
_UIApplicationMain + 212
14
2d_noSuper_education
main (main.mm:13)
15
libdyld.dylib
_start + 4
```

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [ ] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [ ] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

This close #3512 

Guessing the queue ARC lifecycle is wrong during some of compiler optimization

### CODE REVIEW

**Comment by dreampiggy** [comment]
I don't think the crash is because of inline, but because of `SDCallbackQueue` dealloc during the internal `disaptch_queue` been invoked

But anway, since this performance is trival, I still change this inline function into normal function (to help for better stacktrace)

**Comment by cheng-ren** [comment]
When will 5.15.7 be released？

**Comment by dreampiggy** [comment]
Now

**Comment by cheng-ren** [comment]
5.15.7 Still crashing

**Comment by cheng-ren** [comment]
Thread 0 Crashed:
0   libdispatch.dylib                   0x0000000180965a64 dispatch_group_leave.cold.1 + [ : 36] 
1   libdispatch.dylib                   0x00000001809304c8 _dispatch_group_wake
2   BitAutoPlusStore                    0x000000010387430c SDSafeExecute + [SDCallbackQueue.m : 0] 
3   BitAutoPlusStore                    0x00000001038743a0 -[SDCallbackQueue async:] + [SDCallbackQueue.m : 0]

**Comment by cheng-ren** [comment]
QQ: 529639894
可以QQ即时沟通，一起解决下

**Comment by dreampiggy** [comment]
I don't think you're using the correct version, because from your stacktrace, that `SDSafeExecute` is inlined and has no source info.

Or you can create a reproduce demo for me to investigate

**Comment by cheng-ren** [comment]
I provided it to business after use the `pod package` command，Is this the reason? I'm sure the version is correct

**Comment by cheng-ren** [comment]
您好，5.15.7源码引入也依旧是没有能定位到具体行，依旧有crash @dreampiggy 
0   libdispatch.dylib                   0x000000019890aa80 dispatch_group_leave.cold.1 + [ : 36] 
1   libdispatch.dylib                   0x00000001988d5878 _dispatch_group_wake
2   BitAutoPlusStore                    0x0000000107e5ea1c SDSafeExecute + [SDCallbackQueue.m : 0] 
3   BitAutoPlusStore                    0x0000000107e5eaa0 -[SDCallbackQueue async:] + [SDCallbackQueue.m : 0]

**Comment by cheng-ren** [comment]
loadImageWithURL里面SDWebImageRetryFailed这个enum，是不是有一定几率会回调多次呢？ @dreampiggy

**Comment by cheng-ren** [comment]
@dreampiggy 
请还原这个删除内联的commit；发现问题所在了：
在loadImage方法完成回调被调用了多次
业务在loadImage方法内外加了dispatch_group_enter和dispatch_group_leave方法。
请解决回调被多次调用的问题
image

**Pull request merged**
