### PR TITLE
change deployment target to iOS 9 to fix Archiving with Xcode 12

### PR DESCRIPTION
**Pull request by dvshelley**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [ ] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

In order to be able to use Xcode 12 to do an Archive/store build, the minimum deployment target is iOS 9. This commit fixes that across the project files for the 3.x branch.

### CODE REVIEW

**Comment by BeauNouvelle** [comment]
How can we go about getting this merged in some time soon?
It's a nice easy fix....

**Comment by dreampiggy** [comment]
Why only change 3.x branch ?

How about 4.x/5.x together drop the iOS 8 support ?

**Comment by kinarobin** [comment]
@dreampiggy  Emm.. I will change  4.x/5.x together.

**Comment by dreampiggy** [comment]
How about Xcode version ?

Xcode Min Version:
Xcode 10 ? or 11

iOS Min Version:
iOS 8 or 9

**Comment by dreampiggy** [comment]
And. Please, change tvOS Min version as well.

Xcode 12 beta 4 includes SDKs for iOS 14, iPadOS 14, tvOS 14, watchOS 7, and macOS 11. The Xcode 12 beta 4 release supports on-device debugging for iOS 9 and later, tvOS 9 and later, and watchOS 2 and later. Xcode 12 beta 4 requires Apple silicon running macOS Big Sur 11 beta or later, or an Intel-based Mac running macOS Catalina 10.15.4 or later.

See: https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes

**Comment by dreampiggy** [comment]
I think the better idea is not to chagne old version's(3.x/4.x branch)'s deployment target version. Not to merge into that branch.

If you need to specify new version, you can use CocoaPods's Post Installer in your `Podfile`:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
```

**Comment by fruitcoder** [comment]
For the `Package.swift` file there is a backwards compatible way: add a `Package@swift-5.3.swift` file with higher platform versions

**Pull request merged**
