### PR TITLE
Merge 5.x branch into master branch, ready for 5.0.0 release

### PR DESCRIPTION
**Pull request by dreampiggy**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [x] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [x] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: #2285 

### Pull Request Description

Hi everyone.

Today the all pending 5.0.0 changes are now closed. We can ready to release the 5.0.0 version.

The readme have already been updated (change anything original point to '5.x' branch, now in `master`).

The full 5.0 changelog is already been written here, we can also have a check here.

PS: Seems GitHub contains BUG ? I can not create a PR from SDWebImage:5.x -> SDWebImage:master. Anyone can create a PR for this ?

image

### CODE REVIEW

**Comment by dreampiggy** [comment]
@bpoplauschi Seems I can not create a PR from SDWebImage:5.x -> SDWebImage:master. So I use a workaround to do like this.

I've already search all PRs. And change the existing 3 PR (both them are closed) base branch into another. But this does not help. These are: #2454 #2163 #2490.

Could you please also have a try ? Using the create PR link: https://github.com/SDWebImage/SDWebImage/compare/master...5.x

**Comment by zhongwuzw** [comment]
@dreampiggy It says already has a PR for `5.x`, I think we need to close them,  I'll try it.

**Comment by zhongwuzw** [comment]
image

@dreampiggy I have not permissions, can you try change these three PR's source branch from 5.x to other?

image

**Comment by zhongwuzw** [comment]
#2664 for back up.

**Comment by dreampiggy** [comment]
Use that `5.0` branch instead for merging.

**Pull request closed without merging**
