### PR TITLE
add animation loop completion hander on SDAnimatedImageView

### PR DESCRIPTION
**Pull request by kmy504**
### New Pull Request Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar pull request in the [project](https://github.com/rs/SDWebImage/pulls) and found none

* [x] I have updated this branch with the latest master to avoid conflicts (via merge from master or rebase)
* [ ] I have added the required tests to prove the fix/feature I am adding
* [x] I have updated the documentation (if necessary)
* [ ] I have run the tests and they pass
* [x] I have run the lint and it passes (`pod lib lint`)

This merge request fixes / refers to the following issues: ...

### Pull Request Description

SDAnimatedImageView doesn't give any handler to notify animation completion.
Add block property to handle animation completion.( I DO need this feature to implement my project. ;) )

### CODE REVIEW

**Comment by dreampiggy** [comment]
This PR can be implemented by #3115 

Which expose the `SDAnimatedImagePlayer` into public API of `SDAnimatedImageView`.

You can use a proxy object for delegate. Firstly exec the user-provided block, then just proxy to `SDAnimatedImageView` itself.

**Comment by dreampiggy** [comment]
> SDAnimatedImageView doesn't give any handler to notify animation completion.

For now, you can use KVO to observer the loop end event. See that:

```
/**
 Current loop count since its latest animating. This value is KVO Compliance.
 */
@property (nonatomic, assign, readonly) NSUInteger currentLoopCount;
```

**Comment by kmy504** [comment]
OK, I check #3115 PR,
I think that It is not comportable to implement for my main purpose.
This PR close and I will make new PR. Thanks~

**Comment by dreampiggy** [comment]
@kmy504 Why using KVO to `currentLoopCount` can not satisfy your use case ?

>>> You can handle every animation loop completion.

**Comment by kmy504** [comment]
> ```swift
> currentLoopCount
> ```

Actually, I didn't think to use this property. Thank you. I think your exam is satisfied my case.

**Pull request closed without merging**
